#!/usr/bin/env python3
"""
Feedback Review Server
Auto-generated by /feedback skill. Do not edit manually.

Usage:
  python3 feedback-server.py <request.json path> <port>

  port: 0 or omitted = ephemeral (auto-assigned)
"""

import http.server
import json
import os
import platform
import signal
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REQUEST_FILE = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("request.json")
PORT = int(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2] != "0" else 0
WORKSPACE = REQUEST_FILE.parent
HTML_FILE = Path(__file__).parent / "feedback.html"
RESPONSE_FILE = WORKSPACE / "response.json"


def send_notification(title, message):
    """Send a desktop notification. Best-effort."""
    try:
        if platform.system() == "Darwin":
            subprocess.run(
                [
                    "osascript",
                    "-e",
                    f'display notification "{message}" with title "{title}"',
                ],
                capture_output=True,
                timeout=5,
            )
        elif platform.system() == "Linux":
            subprocess.run(
                ["notify-send", title, message], capture_output=True, timeout=5
            )
    except Exception:
        pass


class FeedbackHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path in ("/", "/review"):
            self._serve_review_page()
        elif self.path == "/api/request":
            self._serve_json(REQUEST_FILE.read_bytes())
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        if self.path == "/api/submit":
            self._handle_submit()
        else:
            self.send_response(404)
            self.end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def _serve_review_page(self):
        html = HTML_FILE.read_text(encoding="utf-8")
        request_json = json.dumps(json.loads(REQUEST_FILE.read_text()), indent=2)
        html = html.replace("__REQUEST_JSON__", request_json)
        body = html.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _serve_json(self, data):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(data)

    def _handle_submit(self):
        length = int(self.headers.get("Content-Length", 0))
        body = json.loads(self.rfile.read(length))

        # Build response
        timestamp = datetime.now(timezone.utc).isoformat()
        response = {
            "submitted_at": timestamp,
            "decisions": body.get("decisions", {}),
            "summary": body.get("summary", {}),
        }

        # Write response file atomically
        tmp = RESPONSE_FILE.with_suffix(".tmp")
        tmp.write_text(json.dumps(response, indent=2))
        tmp.rename(RESPONSE_FILE)

        result = json.dumps({"ok": True}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(result)))
        self.end_headers()
        self.wfile.write(result)

        send_notification("Feedback Submitted", "Your feedback has been recorded.")

    def log_message(self, fmt, *args):
        pass  # Suppress access log noise


def main():
    server = http.server.HTTPServer(("127.0.0.1", PORT), FeedbackHandler)
    actual_port = server.server_address[1]

    pid_file = WORKSPACE / "server.pid"
    port_file = WORKSPACE / "server.port"

    pid_file.write_text(str(os.getpid()))
    port_file.write_text(str(actual_port))

    print(f"FEEDBACK_URL=http://127.0.0.1:{actual_port}", flush=True)
    print(f"FEEDBACK_PID={os.getpid()}", flush=True)

    def cleanup(signum=None, frame=None):
        pid_file.unlink(missing_ok=True)
        port_file.unlink(missing_ok=True)
        sys.exit(0)

    signal.signal(signal.SIGTERM, cleanup)

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        cleanup()


if __name__ == "__main__":
    main()
